name: Deploy gihub pages
on:
  push:
    branches: ["main"] #* es en cualquier rama, si quieres solo en main, pon main 
permissions:
  contents: read # para poder escribir en el repositorio, necesario para deployar a github pages
  pages: write # para poder escribir en github pages, necesario para deployar a github pages
  id-token: write # para poder generar un token de acceso, necesario para deployar a github pages
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # action son parte de una pipeline, checkout es una acción que permite clonar el repositorio en el runner
      - run: |
          python -c "
          code = open('src/main.py').read()"
          html=open('templates/index.html').read().replace("{{code}}", code)
          open('public/index.html', 'w').write(html)
          "
      - uses: actions/configure-pages@v5 # para deployar a github pages
      - uses: actions/upload-pages-artifact@v3 # para subir los archivos a github pages
        with:
          path: public # la carpeta que se va a subir a github pages, en este caso es la carpeta public, pero puede ser cualquier carpeta que quieras subir
      - uses: actions/deploy-pages@v3 # para deployar a github pages