name: Tests
on: # Trigger the workflow on push or pull request events 
  push:
    branches: ["*"] #* es en cualquier rama, si quieres solo en main, pon main
  pull_request:
    branches: ["*"]  

jobs: #los test se ejecutan en paralelo, si quieres que se ejecuten en orden, pon dependencias entre ellos
  this_job_run_the_tests:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] #para correr los test en diferentes sistemas operativos
        python-version: ["3.10", "3.11"] #para correr los test en diferentes versiones de python
    runs-on: ${{ matrix.os }} #para correr el test en el sistema operativo definido en la matriz
    steps:
      - uses: actions/checkout@v3 # action son parte de una pipeline, checkout es una acción que permite clonar el repositorio en el runner
      - uses: astral-sh/setup-uv@v5 # para setear uv
        name: Install uv # 
      - run: echo "hola mundo"
      - run: uvx --python ${{ matrix.python-version }} pytest test_code.py 